// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "normalize_ap_fixed_ap_fixed_config17_0_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_ST_fsm_state1 = "1";
const sc_lv<32> normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<16> normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_lv32_3 = "11";
const sc_lv<32> normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_lv32_F = "1111";
const sc_lv<3> normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_lv3_0 = "000";
const sc_lv<17> normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_lv17_1FDF0 = "11111110111110000";
const sc_lv<32> normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_lv32_10 = "10000";
const bool normalize_ap_fixed_ap_fixed_config17_0_0_0::ap_const_boolean_1 = true;

normalize_ap_fixed_ap_fixed_config17_0_0_0::normalize_ap_fixed_ap_fixed_config17_0_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_res_V);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sext_ln708_fu_95_p1 );
    sensitive << ( res_V_preg );

    SC_METHOD(thread_res_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ret_V_fu_79_p2);
    sensitive << ( sext_ln728_fu_75_p1 );

    SC_METHOD(thread_sext_ln708_fu_95_p1);
    sensitive << ( tmp_2_fu_85_p4 );

    SC_METHOD(thread_sext_ln728_fu_75_p1);
    sensitive << ( tmp_1_fu_67_p3 );

    SC_METHOD(thread_tmp_1_fu_67_p3);
    sensitive << ( trunc_ln_fu_57_p4 );

    SC_METHOD(thread_tmp_2_fu_85_p4);
    sensitive << ( ret_V_fu_79_p2 );

    SC_METHOD(thread_trunc_ln_fu_57_p4);
    sensitive << ( p_read );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    res_V_preg = "0000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "normalize_ap_fixed_ap_fixed_config17_0_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, res_V, "(port)res_V");
    sc_trace(mVcdFile, res_V_ap_vld, "(port)res_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, sext_ln708_fu_95_p1, "sext_ln708_fu_95_p1");
    sc_trace(mVcdFile, res_V_preg, "res_V_preg");
    sc_trace(mVcdFile, trunc_ln_fu_57_p4, "trunc_ln_fu_57_p4");
    sc_trace(mVcdFile, tmp_1_fu_67_p3, "tmp_1_fu_67_p3");
    sc_trace(mVcdFile, sext_ln728_fu_75_p1, "sext_ln728_fu_75_p1");
    sc_trace(mVcdFile, ret_V_fu_79_p2, "ret_V_fu_79_p2");
    sc_trace(mVcdFile, tmp_2_fu_85_p4, "tmp_2_fu_85_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

normalize_ap_fixed_ap_fixed_config17_0_0_0::~normalize_ap_fixed_ap_fixed_config17_0_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        res_V_preg = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            res_V_preg = sext_ln708_fu_95_p1.read();
        }
    }
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_res_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V = sext_ln708_fu_95_p1.read();
    } else {
        res_V = res_V_preg.read();
    }
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_res_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_ap_vld = ap_const_logic_1;
    } else {
        res_V_ap_vld = ap_const_logic_0;
    }
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_ret_V_fu_79_p2() {
    ret_V_fu_79_p2 = (!sext_ln728_fu_75_p1.read().is_01() || !ap_const_lv17_1FDF0.is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln728_fu_75_p1.read()) + sc_bigint<17>(ap_const_lv17_1FDF0));
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_sext_ln708_fu_95_p1() {
    sext_ln708_fu_95_p1 = esl_sext<16,14>(tmp_2_fu_85_p4.read());
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_sext_ln728_fu_75_p1() {
    sext_ln728_fu_75_p1 = esl_sext<17,16>(tmp_1_fu_67_p3.read());
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_tmp_1_fu_67_p3() {
    tmp_1_fu_67_p3 = esl_concat<13,3>(trunc_ln_fu_57_p4.read(), ap_const_lv3_0);
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_tmp_2_fu_85_p4() {
    tmp_2_fu_85_p4 = ret_V_fu_79_p2.read().range(16, 3);
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_trunc_ln_fu_57_p4() {
    trunc_ln_fu_57_p4 = p_read.read().range(15, 3);
}

void normalize_ap_fixed_ap_fixed_config17_0_0_0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

