// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _normalize_ap_fixed_ap_fixed_config17_0_0_0_HH_
#define _normalize_ap_fixed_ap_fixed_config17_0_0_0_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct normalize_ap_fixed_ap_fixed_config17_0_0_0 : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > p_read;
    sc_out< sc_lv<16> > res_V;
    sc_out< sc_logic > res_V_ap_vld;


    // Module declarations
    normalize_ap_fixed_ap_fixed_config17_0_0_0(sc_module_name name);
    SC_HAS_PROCESS(normalize_ap_fixed_ap_fixed_config17_0_0_0);

    ~normalize_ap_fixed_ap_fixed_config17_0_0_0();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<16> > sext_ln708_fu_95_p1;
    sc_signal< sc_lv<16> > res_V_preg;
    sc_signal< sc_lv<13> > trunc_ln_fu_57_p4;
    sc_signal< sc_lv<16> > tmp_1_fu_67_p3;
    sc_signal< sc_lv<17> > sext_ln728_fu_75_p1;
    sc_signal< sc_lv<17> > ret_V_fu_79_p2;
    sc_signal< sc_lv<14> > tmp_2_fu_85_p4;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<17> ap_const_lv17_1FDF0;
    static const sc_lv<32> ap_const_lv32_10;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_res_V();
    void thread_res_V_ap_vld();
    void thread_ret_V_fu_79_p2();
    void thread_sext_ln708_fu_95_p1();
    void thread_sext_ln728_fu_75_p1();
    void thread_tmp_1_fu_67_p3();
    void thread_tmp_2_fu_85_p4();
    void thread_trunc_ln_fu_57_p4();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
