// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sigmoid_ap_fixed_ap_fixed_sigmoid_config13_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_0_V_read,
        res_V,
        res_V_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [13:0] data_0_V_read;
output  [13:0] res_V;
output   res_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg res_V_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] sigmoid_table1_address0;
reg    sigmoid_table1_ce0;
wire   [9:0] sigmoid_table1_q0;
wire   [11:0] select_ln850_fu_154_p3;
reg   [11:0] select_ln850_reg_231;
wire   [10:0] trunc_ln167_fu_162_p1;
reg   [10:0] trunc_ln167_reg_236;
wire   [9:0] select_ln169_fu_204_p3;
reg   [9:0] select_ln169_reg_241;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln170_fu_212_p1;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001;
wire   [10:0] tmp_1_fu_102_p4;
wire   [23:0] r_V_fu_94_p3;
wire   [2:0] trunc_ln851_fu_122_p1;
wire   [8:0] p_Result_2_fu_126_p3;
wire  signed [11:0] sext_ln835_fu_112_p1;
wire   [0:0] icmp_ln851_fu_134_p2;
wire   [11:0] ret_V_fu_140_p2;
wire   [0:0] p_Result_s_fu_116_p2;
wire   [11:0] select_ln851_fu_146_p3;
wire   [11:0] index_fu_166_p2;
wire   [0:0] tmp_2_fu_176_p3;
wire   [10:0] add_ln167_1_fu_171_p2;
wire   [10:0] select_ln168_fu_184_p3;
wire   [0:0] tmp_3_fu_196_p3;
wire   [9:0] trunc_ln168_fu_192_p1;
wire   [8:0] lshr_ln_fu_216_p4;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

sigmoid_ap_fixed_ap_fixed_sigmoid_config13_s_sigmoid_table1 #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sigmoid_table1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_table1_address0),
    .ce0(sigmoid_table1_ce0),
    .q0(sigmoid_table1_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln169_reg_241 <= select_ln169_fu_204_p3;
        select_ln850_reg_231 <= select_ln850_fu_154_p3;
        trunc_ln167_reg_236 <= trunc_ln167_fu_162_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_ap_vld = 1'b1;
    end else begin
        res_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sigmoid_table1_ce0 = 1'b1;
    end else begin
        sigmoid_table1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln167_1_fu_171_p2 = (11'd512 + trunc_ln167_reg_236);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign icmp_ln851_fu_134_p2 = ((p_Result_2_fu_126_p3 == 9'd0) ? 1'b1 : 1'b0);

assign index_fu_166_p2 = (12'd512 + select_ln850_reg_231);

assign lshr_ln_fu_216_p4 = {{sigmoid_table1_q0[9:1]}};

assign p_Result_2_fu_126_p3 = {{trunc_ln851_fu_122_p1}, {6'd0}};

assign p_Result_s_fu_116_p2 = (($signed(r_V_fu_94_p3) < $signed(24'd16777201)) ? 1'b1 : 1'b0);

assign r_V_fu_94_p3 = {{data_0_V_read}, {10'd0}};

assign res_V = lshr_ln_fu_216_p4;

assign ret_V_fu_140_p2 = ($signed(12'd1) + $signed(sext_ln835_fu_112_p1));

assign select_ln168_fu_184_p3 = ((tmp_2_fu_176_p3[0:0] === 1'b1) ? 11'd0 : add_ln167_1_fu_171_p2);

assign select_ln169_fu_204_p3 = ((tmp_3_fu_196_p3[0:0] === 1'b1) ? 10'd1023 : trunc_ln168_fu_192_p1);

assign select_ln850_fu_154_p3 = ((p_Result_s_fu_116_p2[0:0] === 1'b1) ? select_ln851_fu_146_p3 : sext_ln835_fu_112_p1);

assign select_ln851_fu_146_p3 = ((icmp_ln851_fu_134_p2[0:0] === 1'b1) ? sext_ln835_fu_112_p1 : ret_V_fu_140_p2);

assign sext_ln835_fu_112_p1 = $signed(tmp_1_fu_102_p4);

assign sigmoid_table1_address0 = zext_ln170_fu_212_p1;

assign tmp_1_fu_102_p4 = {{data_0_V_read[13:3]}};

assign tmp_2_fu_176_p3 = index_fu_166_p2[32'd11];

assign tmp_3_fu_196_p3 = select_ln168_fu_184_p3[32'd10];

assign trunc_ln167_fu_162_p1 = select_ln850_fu_154_p3[10:0];

assign trunc_ln168_fu_192_p1 = select_ln168_fu_184_p3[9:0];

assign trunc_ln851_fu_122_p1 = data_0_V_read[2:0];

assign zext_ln170_fu_212_p1 = select_ln169_reg_241;

endmodule //sigmoid_ap_fixed_ap_fixed_sigmoid_config13_s
