#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 14 17:03:44 CET 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_ia_behav -key {Behavioral:sim_1:Functional:tb_ia} -tclbatch tb_ia.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/se01/micha_maraninchi/kadionikk-master/TP_IA_embarque/mon_ia_2/tb_ia_behav.wcfg -log simulate.log"
xsim tb_ia_behav -key {Behavioral:sim_1:Functional:tb_ia} -tclbatch tb_ia.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/se01/micha_maraninchi/kadionikk-master/TP_IA_embarque/mon_ia_2/tb_ia_behav.wcfg -log simulate.log

