# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/se01/micha_maraninchi/kadionikk-master/TP_IA_embarque/mon_ia_2/mon_ia_2.srcs/sources_1/bd/design_1/ip/design_1_model_nexys_pruned_5_0_0/design_1_model_nexys_pruned_5_0_0.xci
# IP: The module: 'design_1_model_nexys_pruned_5_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/se01/micha_maraninchi/kadionikk-master/TP_IA_embarque/mon_ia_2/mon_ia_2.srcs/sources_1/bd/design_1/ip/design_1_model_nexys_pruned_5_0_0/constraints/model_nexys_pruned_5_hls4ml_prj_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_model_nexys_pruned_5_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/se01/micha_maraninchi/kadionikk-master/TP_IA_embarque/mon_ia_2/mon_ia_2.srcs/sources_1/bd/design_1/ip/design_1_model_nexys_pruned_5_0_0/design_1_model_nexys_pruned_5_0_0.xci
# IP: The module: 'design_1_model_nexys_pruned_5_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/se01/micha_maraninchi/kadionikk-master/TP_IA_embarque/mon_ia_2/mon_ia_2.srcs/sources_1/bd/design_1/ip/design_1_model_nexys_pruned_5_0_0/constraints/model_nexys_pruned_5_hls4ml_prj_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_model_nexys_pruned_5_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
