// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_ap_fixed_ap_fixed_16_6_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        data_32_V_read,
        data_33_V_read,
        data_34_V_read,
        data_35_V_read,
        data_36_V_read,
        data_37_V_read,
        data_38_V_read,
        data_39_V_read,
        data_40_V_read,
        data_41_V_read,
        data_42_V_read,
        data_43_V_read,
        data_44_V_read,
        data_45_V_read,
        data_46_V_read,
        data_47_V_read,
        data_48_V_read,
        data_49_V_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
input  [15:0] data_10_V_read;
input  [15:0] data_11_V_read;
input  [15:0] data_12_V_read;
input  [15:0] data_13_V_read;
input  [15:0] data_14_V_read;
input  [15:0] data_15_V_read;
input  [15:0] data_16_V_read;
input  [15:0] data_17_V_read;
input  [15:0] data_18_V_read;
input  [15:0] data_19_V_read;
input  [15:0] data_20_V_read;
input  [15:0] data_21_V_read;
input  [15:0] data_22_V_read;
input  [15:0] data_23_V_read;
input  [15:0] data_24_V_read;
input  [15:0] data_25_V_read;
input  [15:0] data_26_V_read;
input  [15:0] data_27_V_read;
input  [15:0] data_28_V_read;
input  [15:0] data_29_V_read;
input  [15:0] data_30_V_read;
input  [15:0] data_31_V_read;
input  [15:0] data_32_V_read;
input  [15:0] data_33_V_read;
input  [15:0] data_34_V_read;
input  [15:0] data_35_V_read;
input  [15:0] data_36_V_read;
input  [15:0] data_37_V_read;
input  [15:0] data_38_V_read;
input  [15:0] data_39_V_read;
input  [15:0] data_40_V_read;
input  [15:0] data_41_V_read;
input  [15:0] data_42_V_read;
input  [15:0] data_43_V_read;
input  [15:0] data_44_V_read;
input  [15:0] data_45_V_read;
input  [15:0] data_46_V_read;
input  [15:0] data_47_V_read;
input  [15:0] data_48_V_read;
input  [15:0] data_49_V_read;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln64_fu_1867_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] w11_V_address0;
reg    w11_V_ce0;
wire   [15:0] w11_V_q0;
reg   [0:0] do_init_reg_461;
reg   [15:0] data_0_V_read6_rewind_reg_477;
reg   [15:0] data_1_V_read7_rewind_reg_491;
reg   [15:0] data_2_V_read8_rewind_reg_505;
reg   [15:0] data_3_V_read9_rewind_reg_519;
reg   [15:0] data_4_V_read10_rewind_reg_533;
reg   [15:0] data_5_V_read11_rewind_reg_547;
reg   [15:0] data_6_V_read12_rewind_reg_561;
reg   [15:0] data_7_V_read13_rewind_reg_575;
reg   [15:0] data_8_V_read14_rewind_reg_589;
reg   [15:0] data_9_V_read15_rewind_reg_603;
reg   [15:0] data_10_V_read16_rewind_reg_617;
reg   [15:0] data_11_V_read17_rewind_reg_631;
reg   [15:0] data_12_V_read18_rewind_reg_645;
reg   [15:0] data_13_V_read19_rewind_reg_659;
reg   [15:0] data_14_V_read20_rewind_reg_673;
reg   [15:0] data_15_V_read21_rewind_reg_687;
reg   [15:0] data_16_V_read22_rewind_reg_701;
reg   [15:0] data_17_V_read23_rewind_reg_715;
reg   [15:0] data_18_V_read24_rewind_reg_729;
reg   [15:0] data_19_V_read25_rewind_reg_743;
reg   [15:0] data_20_V_read26_rewind_reg_757;
reg   [15:0] data_21_V_read27_rewind_reg_771;
reg   [15:0] data_22_V_read28_rewind_reg_785;
reg   [15:0] data_23_V_read29_rewind_reg_799;
reg   [15:0] data_24_V_read30_rewind_reg_813;
reg   [15:0] data_25_V_read31_rewind_reg_827;
reg   [15:0] data_26_V_read32_rewind_reg_841;
reg   [15:0] data_27_V_read33_rewind_reg_855;
reg   [15:0] data_28_V_read34_rewind_reg_869;
reg   [15:0] data_29_V_read35_rewind_reg_883;
reg   [15:0] data_30_V_read36_rewind_reg_897;
reg   [15:0] data_31_V_read37_rewind_reg_911;
reg   [15:0] data_32_V_read38_rewind_reg_925;
reg   [15:0] data_33_V_read39_rewind_reg_939;
reg   [15:0] data_34_V_read40_rewind_reg_953;
reg   [15:0] data_35_V_read41_rewind_reg_967;
reg   [15:0] data_36_V_read42_rewind_reg_981;
reg   [15:0] data_37_V_read43_rewind_reg_995;
reg   [15:0] data_38_V_read44_rewind_reg_1009;
reg   [15:0] data_39_V_read45_rewind_reg_1023;
reg   [15:0] data_40_V_read46_rewind_reg_1037;
reg   [15:0] data_41_V_read47_rewind_reg_1051;
reg   [15:0] data_42_V_read48_rewind_reg_1065;
reg   [15:0] data_43_V_read49_rewind_reg_1079;
reg   [15:0] data_44_V_read50_rewind_reg_1093;
reg   [15:0] data_45_V_read51_rewind_reg_1107;
reg   [15:0] data_46_V_read52_rewind_reg_1121;
reg   [15:0] data_47_V_read53_rewind_reg_1135;
reg   [15:0] data_48_V_read54_rewind_reg_1149;
reg   [15:0] data_49_V_read55_rewind_reg_1163;
reg   [5:0] in_index5_reg_1177;
reg   [15:0] data_0_V_read6_phi_reg_1192;
reg   [15:0] data_1_V_read7_phi_reg_1205;
reg   [15:0] data_2_V_read8_phi_reg_1218;
reg   [15:0] data_3_V_read9_phi_reg_1231;
reg   [15:0] data_4_V_read10_phi_reg_1244;
reg   [15:0] data_5_V_read11_phi_reg_1257;
reg   [15:0] data_6_V_read12_phi_reg_1270;
reg   [15:0] data_7_V_read13_phi_reg_1283;
reg   [15:0] data_8_V_read14_phi_reg_1296;
reg   [15:0] data_9_V_read15_phi_reg_1309;
reg   [15:0] data_10_V_read16_phi_reg_1322;
reg   [15:0] data_11_V_read17_phi_reg_1335;
reg   [15:0] data_12_V_read18_phi_reg_1348;
reg   [15:0] data_13_V_read19_phi_reg_1361;
reg   [15:0] data_14_V_read20_phi_reg_1374;
reg   [15:0] data_15_V_read21_phi_reg_1387;
reg   [15:0] data_16_V_read22_phi_reg_1400;
reg   [15:0] data_17_V_read23_phi_reg_1413;
reg   [15:0] data_18_V_read24_phi_reg_1426;
reg   [15:0] data_19_V_read25_phi_reg_1439;
reg   [15:0] data_20_V_read26_phi_reg_1452;
reg   [15:0] data_21_V_read27_phi_reg_1465;
reg   [15:0] data_22_V_read28_phi_reg_1478;
reg   [15:0] data_23_V_read29_phi_reg_1491;
reg   [15:0] data_24_V_read30_phi_reg_1504;
reg   [15:0] data_25_V_read31_phi_reg_1517;
reg   [15:0] data_26_V_read32_phi_reg_1530;
reg   [15:0] data_27_V_read33_phi_reg_1543;
reg   [15:0] data_28_V_read34_phi_reg_1556;
reg   [15:0] data_29_V_read35_phi_reg_1569;
reg   [15:0] data_30_V_read36_phi_reg_1582;
reg   [15:0] data_31_V_read37_phi_reg_1595;
reg   [15:0] data_32_V_read38_phi_reg_1608;
reg   [15:0] data_33_V_read39_phi_reg_1621;
reg   [15:0] data_34_V_read40_phi_reg_1634;
reg   [15:0] data_35_V_read41_phi_reg_1647;
reg   [15:0] data_36_V_read42_phi_reg_1660;
reg   [15:0] data_37_V_read43_phi_reg_1673;
reg   [15:0] data_38_V_read44_phi_reg_1686;
reg   [15:0] data_39_V_read45_phi_reg_1699;
reg   [15:0] data_40_V_read46_phi_reg_1712;
reg   [15:0] data_41_V_read47_phi_reg_1725;
reg   [15:0] data_42_V_read48_phi_reg_1738;
reg   [15:0] data_43_V_read49_phi_reg_1751;
reg   [15:0] data_44_V_read50_phi_reg_1764;
reg   [15:0] data_45_V_read51_phi_reg_1777;
reg   [15:0] data_46_V_read52_phi_reg_1790;
reg   [15:0] data_47_V_read53_phi_reg_1803;
reg   [15:0] data_48_V_read54_phi_reg_1816;
reg   [15:0] data_49_V_read55_phi_reg_1829;
reg   [15:0] res_V_write_assign3_reg_1842;
wire   [5:0] in_index_fu_1861_p2;
reg   [5:0] in_index_reg_2015;
reg   [0:0] icmp_ln64_reg_2020;
reg   [0:0] icmp_ln64_reg_2020_pp0_iter1_reg;
reg   [0:0] icmp_ln64_reg_2020_pp0_iter2_reg;
reg   [0:0] icmp_ln64_reg_2020_pp0_iter3_reg;
reg   [0:0] icmp_ln64_reg_2020_pp0_iter4_reg;
wire   [15:0] tmp_2_fu_1873_p52;
reg  signed [15:0] tmp_2_reg_2024;
reg  signed [15:0] w11_V_load_reg_2029;
wire  signed [28:0] grp_fu_2004_p2;
reg  signed [28:0] r_V_reg_2044;
wire   [15:0] acc_0_V_fu_1994_p2;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] ap_phi_mux_do_init_phi_fu_465_p6;
wire    ap_block_pp0_stage0;
reg   [15:0] ap_phi_mux_data_0_V_read6_rewind_phi_fu_481_p6;
reg   [15:0] ap_phi_mux_data_1_V_read7_rewind_phi_fu_495_p6;
reg   [15:0] ap_phi_mux_data_2_V_read8_rewind_phi_fu_509_p6;
reg   [15:0] ap_phi_mux_data_3_V_read9_rewind_phi_fu_523_p6;
reg   [15:0] ap_phi_mux_data_4_V_read10_rewind_phi_fu_537_p6;
reg   [15:0] ap_phi_mux_data_5_V_read11_rewind_phi_fu_551_p6;
reg   [15:0] ap_phi_mux_data_6_V_read12_rewind_phi_fu_565_p6;
reg   [15:0] ap_phi_mux_data_7_V_read13_rewind_phi_fu_579_p6;
reg   [15:0] ap_phi_mux_data_8_V_read14_rewind_phi_fu_593_p6;
reg   [15:0] ap_phi_mux_data_9_V_read15_rewind_phi_fu_607_p6;
reg   [15:0] ap_phi_mux_data_10_V_read16_rewind_phi_fu_621_p6;
reg   [15:0] ap_phi_mux_data_11_V_read17_rewind_phi_fu_635_p6;
reg   [15:0] ap_phi_mux_data_12_V_read18_rewind_phi_fu_649_p6;
reg   [15:0] ap_phi_mux_data_13_V_read19_rewind_phi_fu_663_p6;
reg   [15:0] ap_phi_mux_data_14_V_read20_rewind_phi_fu_677_p6;
reg   [15:0] ap_phi_mux_data_15_V_read21_rewind_phi_fu_691_p6;
reg   [15:0] ap_phi_mux_data_16_V_read22_rewind_phi_fu_705_p6;
reg   [15:0] ap_phi_mux_data_17_V_read23_rewind_phi_fu_719_p6;
reg   [15:0] ap_phi_mux_data_18_V_read24_rewind_phi_fu_733_p6;
reg   [15:0] ap_phi_mux_data_19_V_read25_rewind_phi_fu_747_p6;
reg   [15:0] ap_phi_mux_data_20_V_read26_rewind_phi_fu_761_p6;
reg   [15:0] ap_phi_mux_data_21_V_read27_rewind_phi_fu_775_p6;
reg   [15:0] ap_phi_mux_data_22_V_read28_rewind_phi_fu_789_p6;
reg   [15:0] ap_phi_mux_data_23_V_read29_rewind_phi_fu_803_p6;
reg   [15:0] ap_phi_mux_data_24_V_read30_rewind_phi_fu_817_p6;
reg   [15:0] ap_phi_mux_data_25_V_read31_rewind_phi_fu_831_p6;
reg   [15:0] ap_phi_mux_data_26_V_read32_rewind_phi_fu_845_p6;
reg   [15:0] ap_phi_mux_data_27_V_read33_rewind_phi_fu_859_p6;
reg   [15:0] ap_phi_mux_data_28_V_read34_rewind_phi_fu_873_p6;
reg   [15:0] ap_phi_mux_data_29_V_read35_rewind_phi_fu_887_p6;
reg   [15:0] ap_phi_mux_data_30_V_read36_rewind_phi_fu_901_p6;
reg   [15:0] ap_phi_mux_data_31_V_read37_rewind_phi_fu_915_p6;
reg   [15:0] ap_phi_mux_data_32_V_read38_rewind_phi_fu_929_p6;
reg   [15:0] ap_phi_mux_data_33_V_read39_rewind_phi_fu_943_p6;
reg   [15:0] ap_phi_mux_data_34_V_read40_rewind_phi_fu_957_p6;
reg   [15:0] ap_phi_mux_data_35_V_read41_rewind_phi_fu_971_p6;
reg   [15:0] ap_phi_mux_data_36_V_read42_rewind_phi_fu_985_p6;
reg   [15:0] ap_phi_mux_data_37_V_read43_rewind_phi_fu_999_p6;
reg   [15:0] ap_phi_mux_data_38_V_read44_rewind_phi_fu_1013_p6;
reg   [15:0] ap_phi_mux_data_39_V_read45_rewind_phi_fu_1027_p6;
reg   [15:0] ap_phi_mux_data_40_V_read46_rewind_phi_fu_1041_p6;
reg   [15:0] ap_phi_mux_data_41_V_read47_rewind_phi_fu_1055_p6;
reg   [15:0] ap_phi_mux_data_42_V_read48_rewind_phi_fu_1069_p6;
reg   [15:0] ap_phi_mux_data_43_V_read49_rewind_phi_fu_1083_p6;
reg   [15:0] ap_phi_mux_data_44_V_read50_rewind_phi_fu_1097_p6;
reg   [15:0] ap_phi_mux_data_45_V_read51_rewind_phi_fu_1111_p6;
reg   [15:0] ap_phi_mux_data_46_V_read52_rewind_phi_fu_1125_p6;
reg   [15:0] ap_phi_mux_data_47_V_read53_rewind_phi_fu_1139_p6;
reg   [15:0] ap_phi_mux_data_48_V_read54_rewind_phi_fu_1153_p6;
reg   [15:0] ap_phi_mux_data_49_V_read55_rewind_phi_fu_1167_p6;
reg   [5:0] ap_phi_mux_in_index5_phi_fu_1181_p6;
wire   [15:0] ap_phi_reg_pp0_iter0_data_0_V_read6_phi_reg_1192;
wire   [15:0] ap_phi_reg_pp0_iter0_data_1_V_read7_phi_reg_1205;
wire   [15:0] ap_phi_reg_pp0_iter0_data_2_V_read8_phi_reg_1218;
wire   [15:0] ap_phi_reg_pp0_iter0_data_3_V_read9_phi_reg_1231;
wire   [15:0] ap_phi_reg_pp0_iter0_data_4_V_read10_phi_reg_1244;
wire   [15:0] ap_phi_reg_pp0_iter0_data_5_V_read11_phi_reg_1257;
wire   [15:0] ap_phi_reg_pp0_iter0_data_6_V_read12_phi_reg_1270;
wire   [15:0] ap_phi_reg_pp0_iter0_data_7_V_read13_phi_reg_1283;
wire   [15:0] ap_phi_reg_pp0_iter0_data_8_V_read14_phi_reg_1296;
wire   [15:0] ap_phi_reg_pp0_iter0_data_9_V_read15_phi_reg_1309;
wire   [15:0] ap_phi_reg_pp0_iter0_data_10_V_read16_phi_reg_1322;
wire   [15:0] ap_phi_reg_pp0_iter0_data_11_V_read17_phi_reg_1335;
wire   [15:0] ap_phi_reg_pp0_iter0_data_12_V_read18_phi_reg_1348;
wire   [15:0] ap_phi_reg_pp0_iter0_data_13_V_read19_phi_reg_1361;
wire   [15:0] ap_phi_reg_pp0_iter0_data_14_V_read20_phi_reg_1374;
wire   [15:0] ap_phi_reg_pp0_iter0_data_15_V_read21_phi_reg_1387;
wire   [15:0] ap_phi_reg_pp0_iter0_data_16_V_read22_phi_reg_1400;
wire   [15:0] ap_phi_reg_pp0_iter0_data_17_V_read23_phi_reg_1413;
wire   [15:0] ap_phi_reg_pp0_iter0_data_18_V_read24_phi_reg_1426;
wire   [15:0] ap_phi_reg_pp0_iter0_data_19_V_read25_phi_reg_1439;
wire   [15:0] ap_phi_reg_pp0_iter0_data_20_V_read26_phi_reg_1452;
wire   [15:0] ap_phi_reg_pp0_iter0_data_21_V_read27_phi_reg_1465;
wire   [15:0] ap_phi_reg_pp0_iter0_data_22_V_read28_phi_reg_1478;
wire   [15:0] ap_phi_reg_pp0_iter0_data_23_V_read29_phi_reg_1491;
wire   [15:0] ap_phi_reg_pp0_iter0_data_24_V_read30_phi_reg_1504;
wire   [15:0] ap_phi_reg_pp0_iter0_data_25_V_read31_phi_reg_1517;
wire   [15:0] ap_phi_reg_pp0_iter0_data_26_V_read32_phi_reg_1530;
wire   [15:0] ap_phi_reg_pp0_iter0_data_27_V_read33_phi_reg_1543;
wire   [15:0] ap_phi_reg_pp0_iter0_data_28_V_read34_phi_reg_1556;
wire   [15:0] ap_phi_reg_pp0_iter0_data_29_V_read35_phi_reg_1569;
wire   [15:0] ap_phi_reg_pp0_iter0_data_30_V_read36_phi_reg_1582;
wire   [15:0] ap_phi_reg_pp0_iter0_data_31_V_read37_phi_reg_1595;
wire   [15:0] ap_phi_reg_pp0_iter0_data_32_V_read38_phi_reg_1608;
wire   [15:0] ap_phi_reg_pp0_iter0_data_33_V_read39_phi_reg_1621;
wire   [15:0] ap_phi_reg_pp0_iter0_data_34_V_read40_phi_reg_1634;
wire   [15:0] ap_phi_reg_pp0_iter0_data_35_V_read41_phi_reg_1647;
wire   [15:0] ap_phi_reg_pp0_iter0_data_36_V_read42_phi_reg_1660;
wire   [15:0] ap_phi_reg_pp0_iter0_data_37_V_read43_phi_reg_1673;
wire   [15:0] ap_phi_reg_pp0_iter0_data_38_V_read44_phi_reg_1686;
wire   [15:0] ap_phi_reg_pp0_iter0_data_39_V_read45_phi_reg_1699;
wire   [15:0] ap_phi_reg_pp0_iter0_data_40_V_read46_phi_reg_1712;
wire   [15:0] ap_phi_reg_pp0_iter0_data_41_V_read47_phi_reg_1725;
wire   [15:0] ap_phi_reg_pp0_iter0_data_42_V_read48_phi_reg_1738;
wire   [15:0] ap_phi_reg_pp0_iter0_data_43_V_read49_phi_reg_1751;
wire   [15:0] ap_phi_reg_pp0_iter0_data_44_V_read50_phi_reg_1764;
wire   [15:0] ap_phi_reg_pp0_iter0_data_45_V_read51_phi_reg_1777;
wire   [15:0] ap_phi_reg_pp0_iter0_data_46_V_read52_phi_reg_1790;
wire   [15:0] ap_phi_reg_pp0_iter0_data_47_V_read53_phi_reg_1803;
wire   [15:0] ap_phi_reg_pp0_iter0_data_48_V_read54_phi_reg_1816;
wire   [15:0] ap_phi_reg_pp0_iter0_data_49_V_read55_phi_reg_1829;
wire   [63:0] zext_ln76_fu_1856_p1;
wire   [15:0] trunc_ln_fu_1985_p4;
reg    grp_fu_2004_ce;
reg   [15:0] ap_return_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_363;
reg    ap_condition_46;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_return_preg = 16'd0;
end

dense_resource_ap_fixed_ap_fixed_16_6_5_3_0_config11_s_w1cud #(
    .DataWidth( 16 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
w11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w11_V_address0),
    .ce0(w11_V_ce0),
    .q0(w11_V_q0)
);

model_2_hls4ml_prj_mux_506_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 16 ),
    .din40_WIDTH( 16 ),
    .din41_WIDTH( 16 ),
    .din42_WIDTH( 16 ),
    .din43_WIDTH( 16 ),
    .din44_WIDTH( 16 ),
    .din45_WIDTH( 16 ),
    .din46_WIDTH( 16 ),
    .din47_WIDTH( 16 ),
    .din48_WIDTH( 16 ),
    .din49_WIDTH( 16 ),
    .din50_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
model_2_hls4ml_prj_mux_506_16_1_1_U1477(
    .din0(data_0_V_read6_phi_reg_1192),
    .din1(data_1_V_read7_phi_reg_1205),
    .din2(data_2_V_read8_phi_reg_1218),
    .din3(data_3_V_read9_phi_reg_1231),
    .din4(data_4_V_read10_phi_reg_1244),
    .din5(data_5_V_read11_phi_reg_1257),
    .din6(data_6_V_read12_phi_reg_1270),
    .din7(data_7_V_read13_phi_reg_1283),
    .din8(data_8_V_read14_phi_reg_1296),
    .din9(data_9_V_read15_phi_reg_1309),
    .din10(data_10_V_read16_phi_reg_1322),
    .din11(data_11_V_read17_phi_reg_1335),
    .din12(data_12_V_read18_phi_reg_1348),
    .din13(data_13_V_read19_phi_reg_1361),
    .din14(data_14_V_read20_phi_reg_1374),
    .din15(data_15_V_read21_phi_reg_1387),
    .din16(data_16_V_read22_phi_reg_1400),
    .din17(data_17_V_read23_phi_reg_1413),
    .din18(data_18_V_read24_phi_reg_1426),
    .din19(data_19_V_read25_phi_reg_1439),
    .din20(data_20_V_read26_phi_reg_1452),
    .din21(data_21_V_read27_phi_reg_1465),
    .din22(data_22_V_read28_phi_reg_1478),
    .din23(data_23_V_read29_phi_reg_1491),
    .din24(data_24_V_read30_phi_reg_1504),
    .din25(data_25_V_read31_phi_reg_1517),
    .din26(data_26_V_read32_phi_reg_1530),
    .din27(data_27_V_read33_phi_reg_1543),
    .din28(data_28_V_read34_phi_reg_1556),
    .din29(data_29_V_read35_phi_reg_1569),
    .din30(data_30_V_read36_phi_reg_1582),
    .din31(data_31_V_read37_phi_reg_1595),
    .din32(data_32_V_read38_phi_reg_1608),
    .din33(data_33_V_read39_phi_reg_1621),
    .din34(data_34_V_read40_phi_reg_1634),
    .din35(data_35_V_read41_phi_reg_1647),
    .din36(data_36_V_read42_phi_reg_1660),
    .din37(data_37_V_read43_phi_reg_1673),
    .din38(data_38_V_read44_phi_reg_1686),
    .din39(data_39_V_read45_phi_reg_1699),
    .din40(data_40_V_read46_phi_reg_1712),
    .din41(data_41_V_read47_phi_reg_1725),
    .din42(data_42_V_read48_phi_reg_1738),
    .din43(data_43_V_read49_phi_reg_1751),
    .din44(data_44_V_read50_phi_reg_1764),
    .din45(data_45_V_read51_phi_reg_1777),
    .din46(data_46_V_read52_phi_reg_1790),
    .din47(data_47_V_read53_phi_reg_1803),
    .din48(data_48_V_read54_phi_reg_1816),
    .din49(data_49_V_read55_phi_reg_1829),
    .din50(in_index5_reg_1177),
    .dout(tmp_2_fu_1873_p52)
);

model_2_hls4ml_prj_mul_mul_16s_16s_29_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
model_2_hls4ml_prj_mul_mul_16s_16s_29_3_1_U1478(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_2_reg_2024),
    .din1(w11_V_load_reg_2029),
    .ce(grp_fu_2004_ce),
    .dout(grp_fu_2004_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            ap_return_preg <= acc_0_V_fu_1994_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_0_V_read6_phi_reg_1192 <= ap_phi_mux_data_0_V_read6_rewind_phi_fu_481_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_0_V_read6_phi_reg_1192 <= data_0_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_0_V_read6_phi_reg_1192 <= ap_phi_reg_pp0_iter0_data_0_V_read6_phi_reg_1192;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_10_V_read16_phi_reg_1322 <= ap_phi_mux_data_10_V_read16_rewind_phi_fu_621_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_10_V_read16_phi_reg_1322 <= data_10_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_10_V_read16_phi_reg_1322 <= ap_phi_reg_pp0_iter0_data_10_V_read16_phi_reg_1322;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_11_V_read17_phi_reg_1335 <= ap_phi_mux_data_11_V_read17_rewind_phi_fu_635_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_11_V_read17_phi_reg_1335 <= data_11_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_11_V_read17_phi_reg_1335 <= ap_phi_reg_pp0_iter0_data_11_V_read17_phi_reg_1335;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_12_V_read18_phi_reg_1348 <= ap_phi_mux_data_12_V_read18_rewind_phi_fu_649_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_12_V_read18_phi_reg_1348 <= data_12_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_12_V_read18_phi_reg_1348 <= ap_phi_reg_pp0_iter0_data_12_V_read18_phi_reg_1348;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_13_V_read19_phi_reg_1361 <= ap_phi_mux_data_13_V_read19_rewind_phi_fu_663_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_13_V_read19_phi_reg_1361 <= data_13_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_13_V_read19_phi_reg_1361 <= ap_phi_reg_pp0_iter0_data_13_V_read19_phi_reg_1361;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_14_V_read20_phi_reg_1374 <= ap_phi_mux_data_14_V_read20_rewind_phi_fu_677_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_14_V_read20_phi_reg_1374 <= data_14_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_14_V_read20_phi_reg_1374 <= ap_phi_reg_pp0_iter0_data_14_V_read20_phi_reg_1374;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_15_V_read21_phi_reg_1387 <= ap_phi_mux_data_15_V_read21_rewind_phi_fu_691_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_15_V_read21_phi_reg_1387 <= data_15_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_15_V_read21_phi_reg_1387 <= ap_phi_reg_pp0_iter0_data_15_V_read21_phi_reg_1387;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_16_V_read22_phi_reg_1400 <= ap_phi_mux_data_16_V_read22_rewind_phi_fu_705_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_16_V_read22_phi_reg_1400 <= data_16_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_16_V_read22_phi_reg_1400 <= ap_phi_reg_pp0_iter0_data_16_V_read22_phi_reg_1400;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_17_V_read23_phi_reg_1413 <= ap_phi_mux_data_17_V_read23_rewind_phi_fu_719_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_17_V_read23_phi_reg_1413 <= data_17_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_17_V_read23_phi_reg_1413 <= ap_phi_reg_pp0_iter0_data_17_V_read23_phi_reg_1413;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_18_V_read24_phi_reg_1426 <= ap_phi_mux_data_18_V_read24_rewind_phi_fu_733_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_18_V_read24_phi_reg_1426 <= data_18_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_18_V_read24_phi_reg_1426 <= ap_phi_reg_pp0_iter0_data_18_V_read24_phi_reg_1426;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_19_V_read25_phi_reg_1439 <= ap_phi_mux_data_19_V_read25_rewind_phi_fu_747_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_19_V_read25_phi_reg_1439 <= data_19_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_19_V_read25_phi_reg_1439 <= ap_phi_reg_pp0_iter0_data_19_V_read25_phi_reg_1439;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_1_V_read7_phi_reg_1205 <= ap_phi_mux_data_1_V_read7_rewind_phi_fu_495_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_1_V_read7_phi_reg_1205 <= data_1_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_1_V_read7_phi_reg_1205 <= ap_phi_reg_pp0_iter0_data_1_V_read7_phi_reg_1205;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_20_V_read26_phi_reg_1452 <= ap_phi_mux_data_20_V_read26_rewind_phi_fu_761_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_20_V_read26_phi_reg_1452 <= data_20_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_20_V_read26_phi_reg_1452 <= ap_phi_reg_pp0_iter0_data_20_V_read26_phi_reg_1452;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_21_V_read27_phi_reg_1465 <= ap_phi_mux_data_21_V_read27_rewind_phi_fu_775_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_21_V_read27_phi_reg_1465 <= data_21_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_21_V_read27_phi_reg_1465 <= ap_phi_reg_pp0_iter0_data_21_V_read27_phi_reg_1465;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_22_V_read28_phi_reg_1478 <= ap_phi_mux_data_22_V_read28_rewind_phi_fu_789_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_22_V_read28_phi_reg_1478 <= data_22_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_22_V_read28_phi_reg_1478 <= ap_phi_reg_pp0_iter0_data_22_V_read28_phi_reg_1478;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_23_V_read29_phi_reg_1491 <= ap_phi_mux_data_23_V_read29_rewind_phi_fu_803_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_23_V_read29_phi_reg_1491 <= data_23_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_23_V_read29_phi_reg_1491 <= ap_phi_reg_pp0_iter0_data_23_V_read29_phi_reg_1491;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_24_V_read30_phi_reg_1504 <= ap_phi_mux_data_24_V_read30_rewind_phi_fu_817_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_24_V_read30_phi_reg_1504 <= data_24_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_24_V_read30_phi_reg_1504 <= ap_phi_reg_pp0_iter0_data_24_V_read30_phi_reg_1504;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_25_V_read31_phi_reg_1517 <= ap_phi_mux_data_25_V_read31_rewind_phi_fu_831_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_25_V_read31_phi_reg_1517 <= data_25_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_25_V_read31_phi_reg_1517 <= ap_phi_reg_pp0_iter0_data_25_V_read31_phi_reg_1517;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_26_V_read32_phi_reg_1530 <= ap_phi_mux_data_26_V_read32_rewind_phi_fu_845_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_26_V_read32_phi_reg_1530 <= data_26_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_26_V_read32_phi_reg_1530 <= ap_phi_reg_pp0_iter0_data_26_V_read32_phi_reg_1530;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_27_V_read33_phi_reg_1543 <= ap_phi_mux_data_27_V_read33_rewind_phi_fu_859_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_27_V_read33_phi_reg_1543 <= data_27_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_27_V_read33_phi_reg_1543 <= ap_phi_reg_pp0_iter0_data_27_V_read33_phi_reg_1543;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_28_V_read34_phi_reg_1556 <= ap_phi_mux_data_28_V_read34_rewind_phi_fu_873_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_28_V_read34_phi_reg_1556 <= data_28_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_28_V_read34_phi_reg_1556 <= ap_phi_reg_pp0_iter0_data_28_V_read34_phi_reg_1556;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_29_V_read35_phi_reg_1569 <= ap_phi_mux_data_29_V_read35_rewind_phi_fu_887_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_29_V_read35_phi_reg_1569 <= data_29_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_29_V_read35_phi_reg_1569 <= ap_phi_reg_pp0_iter0_data_29_V_read35_phi_reg_1569;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_2_V_read8_phi_reg_1218 <= ap_phi_mux_data_2_V_read8_rewind_phi_fu_509_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_2_V_read8_phi_reg_1218 <= data_2_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_2_V_read8_phi_reg_1218 <= ap_phi_reg_pp0_iter0_data_2_V_read8_phi_reg_1218;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_30_V_read36_phi_reg_1582 <= ap_phi_mux_data_30_V_read36_rewind_phi_fu_901_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_30_V_read36_phi_reg_1582 <= data_30_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_30_V_read36_phi_reg_1582 <= ap_phi_reg_pp0_iter0_data_30_V_read36_phi_reg_1582;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_31_V_read37_phi_reg_1595 <= ap_phi_mux_data_31_V_read37_rewind_phi_fu_915_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_31_V_read37_phi_reg_1595 <= data_31_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_31_V_read37_phi_reg_1595 <= ap_phi_reg_pp0_iter0_data_31_V_read37_phi_reg_1595;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_32_V_read38_phi_reg_1608 <= ap_phi_mux_data_32_V_read38_rewind_phi_fu_929_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_32_V_read38_phi_reg_1608 <= data_32_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_32_V_read38_phi_reg_1608 <= ap_phi_reg_pp0_iter0_data_32_V_read38_phi_reg_1608;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_33_V_read39_phi_reg_1621 <= ap_phi_mux_data_33_V_read39_rewind_phi_fu_943_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_33_V_read39_phi_reg_1621 <= data_33_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_33_V_read39_phi_reg_1621 <= ap_phi_reg_pp0_iter0_data_33_V_read39_phi_reg_1621;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_34_V_read40_phi_reg_1634 <= ap_phi_mux_data_34_V_read40_rewind_phi_fu_957_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_34_V_read40_phi_reg_1634 <= data_34_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_34_V_read40_phi_reg_1634 <= ap_phi_reg_pp0_iter0_data_34_V_read40_phi_reg_1634;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_35_V_read41_phi_reg_1647 <= ap_phi_mux_data_35_V_read41_rewind_phi_fu_971_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_35_V_read41_phi_reg_1647 <= data_35_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_35_V_read41_phi_reg_1647 <= ap_phi_reg_pp0_iter0_data_35_V_read41_phi_reg_1647;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_36_V_read42_phi_reg_1660 <= ap_phi_mux_data_36_V_read42_rewind_phi_fu_985_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_36_V_read42_phi_reg_1660 <= data_36_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_36_V_read42_phi_reg_1660 <= ap_phi_reg_pp0_iter0_data_36_V_read42_phi_reg_1660;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_37_V_read43_phi_reg_1673 <= ap_phi_mux_data_37_V_read43_rewind_phi_fu_999_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_37_V_read43_phi_reg_1673 <= data_37_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_37_V_read43_phi_reg_1673 <= ap_phi_reg_pp0_iter0_data_37_V_read43_phi_reg_1673;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_38_V_read44_phi_reg_1686 <= ap_phi_mux_data_38_V_read44_rewind_phi_fu_1013_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_38_V_read44_phi_reg_1686 <= data_38_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_38_V_read44_phi_reg_1686 <= ap_phi_reg_pp0_iter0_data_38_V_read44_phi_reg_1686;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_39_V_read45_phi_reg_1699 <= ap_phi_mux_data_39_V_read45_rewind_phi_fu_1027_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_39_V_read45_phi_reg_1699 <= data_39_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_39_V_read45_phi_reg_1699 <= ap_phi_reg_pp0_iter0_data_39_V_read45_phi_reg_1699;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_3_V_read9_phi_reg_1231 <= ap_phi_mux_data_3_V_read9_rewind_phi_fu_523_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_3_V_read9_phi_reg_1231 <= data_3_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_3_V_read9_phi_reg_1231 <= ap_phi_reg_pp0_iter0_data_3_V_read9_phi_reg_1231;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_40_V_read46_phi_reg_1712 <= ap_phi_mux_data_40_V_read46_rewind_phi_fu_1041_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_40_V_read46_phi_reg_1712 <= data_40_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_40_V_read46_phi_reg_1712 <= ap_phi_reg_pp0_iter0_data_40_V_read46_phi_reg_1712;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_41_V_read47_phi_reg_1725 <= ap_phi_mux_data_41_V_read47_rewind_phi_fu_1055_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_41_V_read47_phi_reg_1725 <= data_41_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_41_V_read47_phi_reg_1725 <= ap_phi_reg_pp0_iter0_data_41_V_read47_phi_reg_1725;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_42_V_read48_phi_reg_1738 <= ap_phi_mux_data_42_V_read48_rewind_phi_fu_1069_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_42_V_read48_phi_reg_1738 <= data_42_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_42_V_read48_phi_reg_1738 <= ap_phi_reg_pp0_iter0_data_42_V_read48_phi_reg_1738;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_43_V_read49_phi_reg_1751 <= ap_phi_mux_data_43_V_read49_rewind_phi_fu_1083_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_43_V_read49_phi_reg_1751 <= data_43_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_43_V_read49_phi_reg_1751 <= ap_phi_reg_pp0_iter0_data_43_V_read49_phi_reg_1751;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_44_V_read50_phi_reg_1764 <= ap_phi_mux_data_44_V_read50_rewind_phi_fu_1097_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_44_V_read50_phi_reg_1764 <= data_44_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_44_V_read50_phi_reg_1764 <= ap_phi_reg_pp0_iter0_data_44_V_read50_phi_reg_1764;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_45_V_read51_phi_reg_1777 <= ap_phi_mux_data_45_V_read51_rewind_phi_fu_1111_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_45_V_read51_phi_reg_1777 <= data_45_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_45_V_read51_phi_reg_1777 <= ap_phi_reg_pp0_iter0_data_45_V_read51_phi_reg_1777;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_46_V_read52_phi_reg_1790 <= ap_phi_mux_data_46_V_read52_rewind_phi_fu_1125_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_46_V_read52_phi_reg_1790 <= data_46_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_46_V_read52_phi_reg_1790 <= ap_phi_reg_pp0_iter0_data_46_V_read52_phi_reg_1790;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_47_V_read53_phi_reg_1803 <= ap_phi_mux_data_47_V_read53_rewind_phi_fu_1139_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_47_V_read53_phi_reg_1803 <= data_47_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_47_V_read53_phi_reg_1803 <= ap_phi_reg_pp0_iter0_data_47_V_read53_phi_reg_1803;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_48_V_read54_phi_reg_1816 <= ap_phi_mux_data_48_V_read54_rewind_phi_fu_1153_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_48_V_read54_phi_reg_1816 <= data_48_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_48_V_read54_phi_reg_1816 <= ap_phi_reg_pp0_iter0_data_48_V_read54_phi_reg_1816;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_49_V_read55_phi_reg_1829 <= ap_phi_mux_data_49_V_read55_rewind_phi_fu_1167_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_49_V_read55_phi_reg_1829 <= data_49_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_49_V_read55_phi_reg_1829 <= ap_phi_reg_pp0_iter0_data_49_V_read55_phi_reg_1829;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_4_V_read10_phi_reg_1244 <= ap_phi_mux_data_4_V_read10_rewind_phi_fu_537_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_4_V_read10_phi_reg_1244 <= data_4_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_4_V_read10_phi_reg_1244 <= ap_phi_reg_pp0_iter0_data_4_V_read10_phi_reg_1244;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_5_V_read11_phi_reg_1257 <= ap_phi_mux_data_5_V_read11_rewind_phi_fu_551_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_5_V_read11_phi_reg_1257 <= data_5_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_5_V_read11_phi_reg_1257 <= ap_phi_reg_pp0_iter0_data_5_V_read11_phi_reg_1257;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_6_V_read12_phi_reg_1270 <= ap_phi_mux_data_6_V_read12_rewind_phi_fu_565_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_6_V_read12_phi_reg_1270 <= data_6_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_6_V_read12_phi_reg_1270 <= ap_phi_reg_pp0_iter0_data_6_V_read12_phi_reg_1270;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_7_V_read13_phi_reg_1283 <= ap_phi_mux_data_7_V_read13_rewind_phi_fu_579_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_7_V_read13_phi_reg_1283 <= data_7_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_7_V_read13_phi_reg_1283 <= ap_phi_reg_pp0_iter0_data_7_V_read13_phi_reg_1283;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_8_V_read14_phi_reg_1296 <= ap_phi_mux_data_8_V_read14_rewind_phi_fu_593_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_8_V_read14_phi_reg_1296 <= data_8_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_8_V_read14_phi_reg_1296 <= ap_phi_reg_pp0_iter0_data_8_V_read14_phi_reg_1296;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd0)) begin
            data_9_V_read15_phi_reg_1309 <= ap_phi_mux_data_9_V_read15_rewind_phi_fu_607_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_465_p6 == 1'd1)) begin
            data_9_V_read15_phi_reg_1309 <= data_9_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_9_V_read15_phi_reg_1309 <= ap_phi_reg_pp0_iter0_data_9_V_read15_phi_reg_1309;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_461 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_461 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index5_reg_1177 <= in_index_reg_2015;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index5_reg_1177 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        res_V_write_assign3_reg_1842 <= acc_0_V_fu_1994_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_write_assign3_reg_1842 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_0_V_read6_rewind_reg_477 <= data_0_V_read6_phi_reg_1192;
        data_10_V_read16_rewind_reg_617 <= data_10_V_read16_phi_reg_1322;
        data_11_V_read17_rewind_reg_631 <= data_11_V_read17_phi_reg_1335;
        data_12_V_read18_rewind_reg_645 <= data_12_V_read18_phi_reg_1348;
        data_13_V_read19_rewind_reg_659 <= data_13_V_read19_phi_reg_1361;
        data_14_V_read20_rewind_reg_673 <= data_14_V_read20_phi_reg_1374;
        data_15_V_read21_rewind_reg_687 <= data_15_V_read21_phi_reg_1387;
        data_16_V_read22_rewind_reg_701 <= data_16_V_read22_phi_reg_1400;
        data_17_V_read23_rewind_reg_715 <= data_17_V_read23_phi_reg_1413;
        data_18_V_read24_rewind_reg_729 <= data_18_V_read24_phi_reg_1426;
        data_19_V_read25_rewind_reg_743 <= data_19_V_read25_phi_reg_1439;
        data_1_V_read7_rewind_reg_491 <= data_1_V_read7_phi_reg_1205;
        data_20_V_read26_rewind_reg_757 <= data_20_V_read26_phi_reg_1452;
        data_21_V_read27_rewind_reg_771 <= data_21_V_read27_phi_reg_1465;
        data_22_V_read28_rewind_reg_785 <= data_22_V_read28_phi_reg_1478;
        data_23_V_read29_rewind_reg_799 <= data_23_V_read29_phi_reg_1491;
        data_24_V_read30_rewind_reg_813 <= data_24_V_read30_phi_reg_1504;
        data_25_V_read31_rewind_reg_827 <= data_25_V_read31_phi_reg_1517;
        data_26_V_read32_rewind_reg_841 <= data_26_V_read32_phi_reg_1530;
        data_27_V_read33_rewind_reg_855 <= data_27_V_read33_phi_reg_1543;
        data_28_V_read34_rewind_reg_869 <= data_28_V_read34_phi_reg_1556;
        data_29_V_read35_rewind_reg_883 <= data_29_V_read35_phi_reg_1569;
        data_2_V_read8_rewind_reg_505 <= data_2_V_read8_phi_reg_1218;
        data_30_V_read36_rewind_reg_897 <= data_30_V_read36_phi_reg_1582;
        data_31_V_read37_rewind_reg_911 <= data_31_V_read37_phi_reg_1595;
        data_32_V_read38_rewind_reg_925 <= data_32_V_read38_phi_reg_1608;
        data_33_V_read39_rewind_reg_939 <= data_33_V_read39_phi_reg_1621;
        data_34_V_read40_rewind_reg_953 <= data_34_V_read40_phi_reg_1634;
        data_35_V_read41_rewind_reg_967 <= data_35_V_read41_phi_reg_1647;
        data_36_V_read42_rewind_reg_981 <= data_36_V_read42_phi_reg_1660;
        data_37_V_read43_rewind_reg_995 <= data_37_V_read43_phi_reg_1673;
        data_38_V_read44_rewind_reg_1009 <= data_38_V_read44_phi_reg_1686;
        data_39_V_read45_rewind_reg_1023 <= data_39_V_read45_phi_reg_1699;
        data_3_V_read9_rewind_reg_519 <= data_3_V_read9_phi_reg_1231;
        data_40_V_read46_rewind_reg_1037 <= data_40_V_read46_phi_reg_1712;
        data_41_V_read47_rewind_reg_1051 <= data_41_V_read47_phi_reg_1725;
        data_42_V_read48_rewind_reg_1065 <= data_42_V_read48_phi_reg_1738;
        data_43_V_read49_rewind_reg_1079 <= data_43_V_read49_phi_reg_1751;
        data_44_V_read50_rewind_reg_1093 <= data_44_V_read50_phi_reg_1764;
        data_45_V_read51_rewind_reg_1107 <= data_45_V_read51_phi_reg_1777;
        data_46_V_read52_rewind_reg_1121 <= data_46_V_read52_phi_reg_1790;
        data_47_V_read53_rewind_reg_1135 <= data_47_V_read53_phi_reg_1803;
        data_48_V_read54_rewind_reg_1149 <= data_48_V_read54_phi_reg_1816;
        data_49_V_read55_rewind_reg_1163 <= data_49_V_read55_phi_reg_1829;
        data_4_V_read10_rewind_reg_533 <= data_4_V_read10_phi_reg_1244;
        data_5_V_read11_rewind_reg_547 <= data_5_V_read11_phi_reg_1257;
        data_6_V_read12_rewind_reg_561 <= data_6_V_read12_phi_reg_1270;
        data_7_V_read13_rewind_reg_575 <= data_7_V_read13_phi_reg_1283;
        data_8_V_read14_rewind_reg_589 <= data_8_V_read14_phi_reg_1296;
        data_9_V_read15_rewind_reg_603 <= data_9_V_read15_phi_reg_1309;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln64_reg_2020 <= icmp_ln64_fu_1867_p2;
        icmp_ln64_reg_2020_pp0_iter1_reg <= icmp_ln64_reg_2020;
        tmp_2_reg_2024 <= tmp_2_fu_1873_p52;
        w11_V_load_reg_2029 <= w11_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln64_reg_2020_pp0_iter2_reg <= icmp_ln64_reg_2020_pp0_iter1_reg;
        icmp_ln64_reg_2020_pp0_iter3_reg <= icmp_ln64_reg_2020_pp0_iter2_reg;
        icmp_ln64_reg_2020_pp0_iter4_reg <= icmp_ln64_reg_2020_pp0_iter3_reg;
        r_V_reg_2044 <= grp_fu_2004_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_reg_2015 <= in_index_fu_1861_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_0_V_read6_rewind_phi_fu_481_p6 = data_0_V_read6_phi_reg_1192;
    end else begin
        ap_phi_mux_data_0_V_read6_rewind_phi_fu_481_p6 = data_0_V_read6_rewind_reg_477;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_10_V_read16_rewind_phi_fu_621_p6 = data_10_V_read16_phi_reg_1322;
    end else begin
        ap_phi_mux_data_10_V_read16_rewind_phi_fu_621_p6 = data_10_V_read16_rewind_reg_617;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_11_V_read17_rewind_phi_fu_635_p6 = data_11_V_read17_phi_reg_1335;
    end else begin
        ap_phi_mux_data_11_V_read17_rewind_phi_fu_635_p6 = data_11_V_read17_rewind_reg_631;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_12_V_read18_rewind_phi_fu_649_p6 = data_12_V_read18_phi_reg_1348;
    end else begin
        ap_phi_mux_data_12_V_read18_rewind_phi_fu_649_p6 = data_12_V_read18_rewind_reg_645;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_13_V_read19_rewind_phi_fu_663_p6 = data_13_V_read19_phi_reg_1361;
    end else begin
        ap_phi_mux_data_13_V_read19_rewind_phi_fu_663_p6 = data_13_V_read19_rewind_reg_659;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_14_V_read20_rewind_phi_fu_677_p6 = data_14_V_read20_phi_reg_1374;
    end else begin
        ap_phi_mux_data_14_V_read20_rewind_phi_fu_677_p6 = data_14_V_read20_rewind_reg_673;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_15_V_read21_rewind_phi_fu_691_p6 = data_15_V_read21_phi_reg_1387;
    end else begin
        ap_phi_mux_data_15_V_read21_rewind_phi_fu_691_p6 = data_15_V_read21_rewind_reg_687;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_16_V_read22_rewind_phi_fu_705_p6 = data_16_V_read22_phi_reg_1400;
    end else begin
        ap_phi_mux_data_16_V_read22_rewind_phi_fu_705_p6 = data_16_V_read22_rewind_reg_701;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_17_V_read23_rewind_phi_fu_719_p6 = data_17_V_read23_phi_reg_1413;
    end else begin
        ap_phi_mux_data_17_V_read23_rewind_phi_fu_719_p6 = data_17_V_read23_rewind_reg_715;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_18_V_read24_rewind_phi_fu_733_p6 = data_18_V_read24_phi_reg_1426;
    end else begin
        ap_phi_mux_data_18_V_read24_rewind_phi_fu_733_p6 = data_18_V_read24_rewind_reg_729;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_19_V_read25_rewind_phi_fu_747_p6 = data_19_V_read25_phi_reg_1439;
    end else begin
        ap_phi_mux_data_19_V_read25_rewind_phi_fu_747_p6 = data_19_V_read25_rewind_reg_743;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_1_V_read7_rewind_phi_fu_495_p6 = data_1_V_read7_phi_reg_1205;
    end else begin
        ap_phi_mux_data_1_V_read7_rewind_phi_fu_495_p6 = data_1_V_read7_rewind_reg_491;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_20_V_read26_rewind_phi_fu_761_p6 = data_20_V_read26_phi_reg_1452;
    end else begin
        ap_phi_mux_data_20_V_read26_rewind_phi_fu_761_p6 = data_20_V_read26_rewind_reg_757;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_21_V_read27_rewind_phi_fu_775_p6 = data_21_V_read27_phi_reg_1465;
    end else begin
        ap_phi_mux_data_21_V_read27_rewind_phi_fu_775_p6 = data_21_V_read27_rewind_reg_771;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_22_V_read28_rewind_phi_fu_789_p6 = data_22_V_read28_phi_reg_1478;
    end else begin
        ap_phi_mux_data_22_V_read28_rewind_phi_fu_789_p6 = data_22_V_read28_rewind_reg_785;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_23_V_read29_rewind_phi_fu_803_p6 = data_23_V_read29_phi_reg_1491;
    end else begin
        ap_phi_mux_data_23_V_read29_rewind_phi_fu_803_p6 = data_23_V_read29_rewind_reg_799;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_24_V_read30_rewind_phi_fu_817_p6 = data_24_V_read30_phi_reg_1504;
    end else begin
        ap_phi_mux_data_24_V_read30_rewind_phi_fu_817_p6 = data_24_V_read30_rewind_reg_813;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_25_V_read31_rewind_phi_fu_831_p6 = data_25_V_read31_phi_reg_1517;
    end else begin
        ap_phi_mux_data_25_V_read31_rewind_phi_fu_831_p6 = data_25_V_read31_rewind_reg_827;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_26_V_read32_rewind_phi_fu_845_p6 = data_26_V_read32_phi_reg_1530;
    end else begin
        ap_phi_mux_data_26_V_read32_rewind_phi_fu_845_p6 = data_26_V_read32_rewind_reg_841;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_27_V_read33_rewind_phi_fu_859_p6 = data_27_V_read33_phi_reg_1543;
    end else begin
        ap_phi_mux_data_27_V_read33_rewind_phi_fu_859_p6 = data_27_V_read33_rewind_reg_855;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_28_V_read34_rewind_phi_fu_873_p6 = data_28_V_read34_phi_reg_1556;
    end else begin
        ap_phi_mux_data_28_V_read34_rewind_phi_fu_873_p6 = data_28_V_read34_rewind_reg_869;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_29_V_read35_rewind_phi_fu_887_p6 = data_29_V_read35_phi_reg_1569;
    end else begin
        ap_phi_mux_data_29_V_read35_rewind_phi_fu_887_p6 = data_29_V_read35_rewind_reg_883;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_2_V_read8_rewind_phi_fu_509_p6 = data_2_V_read8_phi_reg_1218;
    end else begin
        ap_phi_mux_data_2_V_read8_rewind_phi_fu_509_p6 = data_2_V_read8_rewind_reg_505;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_30_V_read36_rewind_phi_fu_901_p6 = data_30_V_read36_phi_reg_1582;
    end else begin
        ap_phi_mux_data_30_V_read36_rewind_phi_fu_901_p6 = data_30_V_read36_rewind_reg_897;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_31_V_read37_rewind_phi_fu_915_p6 = data_31_V_read37_phi_reg_1595;
    end else begin
        ap_phi_mux_data_31_V_read37_rewind_phi_fu_915_p6 = data_31_V_read37_rewind_reg_911;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_32_V_read38_rewind_phi_fu_929_p6 = data_32_V_read38_phi_reg_1608;
    end else begin
        ap_phi_mux_data_32_V_read38_rewind_phi_fu_929_p6 = data_32_V_read38_rewind_reg_925;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_33_V_read39_rewind_phi_fu_943_p6 = data_33_V_read39_phi_reg_1621;
    end else begin
        ap_phi_mux_data_33_V_read39_rewind_phi_fu_943_p6 = data_33_V_read39_rewind_reg_939;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_34_V_read40_rewind_phi_fu_957_p6 = data_34_V_read40_phi_reg_1634;
    end else begin
        ap_phi_mux_data_34_V_read40_rewind_phi_fu_957_p6 = data_34_V_read40_rewind_reg_953;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_35_V_read41_rewind_phi_fu_971_p6 = data_35_V_read41_phi_reg_1647;
    end else begin
        ap_phi_mux_data_35_V_read41_rewind_phi_fu_971_p6 = data_35_V_read41_rewind_reg_967;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_36_V_read42_rewind_phi_fu_985_p6 = data_36_V_read42_phi_reg_1660;
    end else begin
        ap_phi_mux_data_36_V_read42_rewind_phi_fu_985_p6 = data_36_V_read42_rewind_reg_981;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_37_V_read43_rewind_phi_fu_999_p6 = data_37_V_read43_phi_reg_1673;
    end else begin
        ap_phi_mux_data_37_V_read43_rewind_phi_fu_999_p6 = data_37_V_read43_rewind_reg_995;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_38_V_read44_rewind_phi_fu_1013_p6 = data_38_V_read44_phi_reg_1686;
    end else begin
        ap_phi_mux_data_38_V_read44_rewind_phi_fu_1013_p6 = data_38_V_read44_rewind_reg_1009;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_39_V_read45_rewind_phi_fu_1027_p6 = data_39_V_read45_phi_reg_1699;
    end else begin
        ap_phi_mux_data_39_V_read45_rewind_phi_fu_1027_p6 = data_39_V_read45_rewind_reg_1023;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_3_V_read9_rewind_phi_fu_523_p6 = data_3_V_read9_phi_reg_1231;
    end else begin
        ap_phi_mux_data_3_V_read9_rewind_phi_fu_523_p6 = data_3_V_read9_rewind_reg_519;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_40_V_read46_rewind_phi_fu_1041_p6 = data_40_V_read46_phi_reg_1712;
    end else begin
        ap_phi_mux_data_40_V_read46_rewind_phi_fu_1041_p6 = data_40_V_read46_rewind_reg_1037;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_41_V_read47_rewind_phi_fu_1055_p6 = data_41_V_read47_phi_reg_1725;
    end else begin
        ap_phi_mux_data_41_V_read47_rewind_phi_fu_1055_p6 = data_41_V_read47_rewind_reg_1051;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_42_V_read48_rewind_phi_fu_1069_p6 = data_42_V_read48_phi_reg_1738;
    end else begin
        ap_phi_mux_data_42_V_read48_rewind_phi_fu_1069_p6 = data_42_V_read48_rewind_reg_1065;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_43_V_read49_rewind_phi_fu_1083_p6 = data_43_V_read49_phi_reg_1751;
    end else begin
        ap_phi_mux_data_43_V_read49_rewind_phi_fu_1083_p6 = data_43_V_read49_rewind_reg_1079;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_44_V_read50_rewind_phi_fu_1097_p6 = data_44_V_read50_phi_reg_1764;
    end else begin
        ap_phi_mux_data_44_V_read50_rewind_phi_fu_1097_p6 = data_44_V_read50_rewind_reg_1093;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_45_V_read51_rewind_phi_fu_1111_p6 = data_45_V_read51_phi_reg_1777;
    end else begin
        ap_phi_mux_data_45_V_read51_rewind_phi_fu_1111_p6 = data_45_V_read51_rewind_reg_1107;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_46_V_read52_rewind_phi_fu_1125_p6 = data_46_V_read52_phi_reg_1790;
    end else begin
        ap_phi_mux_data_46_V_read52_rewind_phi_fu_1125_p6 = data_46_V_read52_rewind_reg_1121;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_47_V_read53_rewind_phi_fu_1139_p6 = data_47_V_read53_phi_reg_1803;
    end else begin
        ap_phi_mux_data_47_V_read53_rewind_phi_fu_1139_p6 = data_47_V_read53_rewind_reg_1135;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_48_V_read54_rewind_phi_fu_1153_p6 = data_48_V_read54_phi_reg_1816;
    end else begin
        ap_phi_mux_data_48_V_read54_rewind_phi_fu_1153_p6 = data_48_V_read54_rewind_reg_1149;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_49_V_read55_rewind_phi_fu_1167_p6 = data_49_V_read55_phi_reg_1829;
    end else begin
        ap_phi_mux_data_49_V_read55_rewind_phi_fu_1167_p6 = data_49_V_read55_rewind_reg_1163;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_4_V_read10_rewind_phi_fu_537_p6 = data_4_V_read10_phi_reg_1244;
    end else begin
        ap_phi_mux_data_4_V_read10_rewind_phi_fu_537_p6 = data_4_V_read10_rewind_reg_533;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_5_V_read11_rewind_phi_fu_551_p6 = data_5_V_read11_phi_reg_1257;
    end else begin
        ap_phi_mux_data_5_V_read11_rewind_phi_fu_551_p6 = data_5_V_read11_rewind_reg_547;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_6_V_read12_rewind_phi_fu_565_p6 = data_6_V_read12_phi_reg_1270;
    end else begin
        ap_phi_mux_data_6_V_read12_rewind_phi_fu_565_p6 = data_6_V_read12_rewind_reg_561;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_7_V_read13_rewind_phi_fu_579_p6 = data_7_V_read13_phi_reg_1283;
    end else begin
        ap_phi_mux_data_7_V_read13_rewind_phi_fu_579_p6 = data_7_V_read13_rewind_reg_575;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_8_V_read14_rewind_phi_fu_593_p6 = data_8_V_read14_phi_reg_1296;
    end else begin
        ap_phi_mux_data_8_V_read14_rewind_phi_fu_593_p6 = data_8_V_read14_rewind_reg_589;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2020 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_9_V_read15_rewind_phi_fu_607_p6 = data_9_V_read15_phi_reg_1309;
    end else begin
        ap_phi_mux_data_9_V_read15_rewind_phi_fu_607_p6 = data_9_V_read15_rewind_reg_603;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_363)) begin
        if ((icmp_ln64_reg_2020 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_465_p6 = 1'd1;
        end else if ((icmp_ln64_reg_2020 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_465_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_465_p6 = do_init_reg_461;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_465_p6 = do_init_reg_461;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_363)) begin
        if ((icmp_ln64_reg_2020 == 1'd1)) begin
            ap_phi_mux_in_index5_phi_fu_1181_p6 = 6'd0;
        end else if ((icmp_ln64_reg_2020 == 1'd0)) begin
            ap_phi_mux_in_index5_phi_fu_1181_p6 = in_index_reg_2015;
        end else begin
            ap_phi_mux_in_index5_phi_fu_1181_p6 = in_index5_reg_1177;
        end
    end else begin
        ap_phi_mux_in_index5_phi_fu_1181_p6 = in_index5_reg_1177;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_fu_1867_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2020_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_return = acc_0_V_fu_1994_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2004_ce = 1'b1;
    end else begin
        grp_fu_2004_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_V_ce0 = 1'b1;
    end else begin
        w11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_1994_p2 = (trunc_ln_fu_1985_p4 + res_V_write_assign3_reg_1842);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_363 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_46 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_data_0_V_read6_phi_reg_1192 = 'bx;

assign ap_phi_reg_pp0_iter0_data_10_V_read16_phi_reg_1322 = 'bx;

assign ap_phi_reg_pp0_iter0_data_11_V_read17_phi_reg_1335 = 'bx;

assign ap_phi_reg_pp0_iter0_data_12_V_read18_phi_reg_1348 = 'bx;

assign ap_phi_reg_pp0_iter0_data_13_V_read19_phi_reg_1361 = 'bx;

assign ap_phi_reg_pp0_iter0_data_14_V_read20_phi_reg_1374 = 'bx;

assign ap_phi_reg_pp0_iter0_data_15_V_read21_phi_reg_1387 = 'bx;

assign ap_phi_reg_pp0_iter0_data_16_V_read22_phi_reg_1400 = 'bx;

assign ap_phi_reg_pp0_iter0_data_17_V_read23_phi_reg_1413 = 'bx;

assign ap_phi_reg_pp0_iter0_data_18_V_read24_phi_reg_1426 = 'bx;

assign ap_phi_reg_pp0_iter0_data_19_V_read25_phi_reg_1439 = 'bx;

assign ap_phi_reg_pp0_iter0_data_1_V_read7_phi_reg_1205 = 'bx;

assign ap_phi_reg_pp0_iter0_data_20_V_read26_phi_reg_1452 = 'bx;

assign ap_phi_reg_pp0_iter0_data_21_V_read27_phi_reg_1465 = 'bx;

assign ap_phi_reg_pp0_iter0_data_22_V_read28_phi_reg_1478 = 'bx;

assign ap_phi_reg_pp0_iter0_data_23_V_read29_phi_reg_1491 = 'bx;

assign ap_phi_reg_pp0_iter0_data_24_V_read30_phi_reg_1504 = 'bx;

assign ap_phi_reg_pp0_iter0_data_25_V_read31_phi_reg_1517 = 'bx;

assign ap_phi_reg_pp0_iter0_data_26_V_read32_phi_reg_1530 = 'bx;

assign ap_phi_reg_pp0_iter0_data_27_V_read33_phi_reg_1543 = 'bx;

assign ap_phi_reg_pp0_iter0_data_28_V_read34_phi_reg_1556 = 'bx;

assign ap_phi_reg_pp0_iter0_data_29_V_read35_phi_reg_1569 = 'bx;

assign ap_phi_reg_pp0_iter0_data_2_V_read8_phi_reg_1218 = 'bx;

assign ap_phi_reg_pp0_iter0_data_30_V_read36_phi_reg_1582 = 'bx;

assign ap_phi_reg_pp0_iter0_data_31_V_read37_phi_reg_1595 = 'bx;

assign ap_phi_reg_pp0_iter0_data_32_V_read38_phi_reg_1608 = 'bx;

assign ap_phi_reg_pp0_iter0_data_33_V_read39_phi_reg_1621 = 'bx;

assign ap_phi_reg_pp0_iter0_data_34_V_read40_phi_reg_1634 = 'bx;

assign ap_phi_reg_pp0_iter0_data_35_V_read41_phi_reg_1647 = 'bx;

assign ap_phi_reg_pp0_iter0_data_36_V_read42_phi_reg_1660 = 'bx;

assign ap_phi_reg_pp0_iter0_data_37_V_read43_phi_reg_1673 = 'bx;

assign ap_phi_reg_pp0_iter0_data_38_V_read44_phi_reg_1686 = 'bx;

assign ap_phi_reg_pp0_iter0_data_39_V_read45_phi_reg_1699 = 'bx;

assign ap_phi_reg_pp0_iter0_data_3_V_read9_phi_reg_1231 = 'bx;

assign ap_phi_reg_pp0_iter0_data_40_V_read46_phi_reg_1712 = 'bx;

assign ap_phi_reg_pp0_iter0_data_41_V_read47_phi_reg_1725 = 'bx;

assign ap_phi_reg_pp0_iter0_data_42_V_read48_phi_reg_1738 = 'bx;

assign ap_phi_reg_pp0_iter0_data_43_V_read49_phi_reg_1751 = 'bx;

assign ap_phi_reg_pp0_iter0_data_44_V_read50_phi_reg_1764 = 'bx;

assign ap_phi_reg_pp0_iter0_data_45_V_read51_phi_reg_1777 = 'bx;

assign ap_phi_reg_pp0_iter0_data_46_V_read52_phi_reg_1790 = 'bx;

assign ap_phi_reg_pp0_iter0_data_47_V_read53_phi_reg_1803 = 'bx;

assign ap_phi_reg_pp0_iter0_data_48_V_read54_phi_reg_1816 = 'bx;

assign ap_phi_reg_pp0_iter0_data_49_V_read55_phi_reg_1829 = 'bx;

assign ap_phi_reg_pp0_iter0_data_4_V_read10_phi_reg_1244 = 'bx;

assign ap_phi_reg_pp0_iter0_data_5_V_read11_phi_reg_1257 = 'bx;

assign ap_phi_reg_pp0_iter0_data_6_V_read12_phi_reg_1270 = 'bx;

assign ap_phi_reg_pp0_iter0_data_7_V_read13_phi_reg_1283 = 'bx;

assign ap_phi_reg_pp0_iter0_data_8_V_read14_phi_reg_1296 = 'bx;

assign ap_phi_reg_pp0_iter0_data_9_V_read15_phi_reg_1309 = 'bx;

assign icmp_ln64_fu_1867_p2 = ((ap_phi_mux_in_index5_phi_fu_1181_p6 == 6'd49) ? 1'b1 : 1'b0);

assign in_index_fu_1861_p2 = (ap_phi_mux_in_index5_phi_fu_1181_p6 + 6'd1);

assign trunc_ln_fu_1985_p4 = {{r_V_reg_2044[28:13]}};

assign w11_V_address0 = zext_ln76_fu_1856_p1;

assign zext_ln76_fu_1856_p1 = ap_phi_mux_in_index5_phi_fu_1181_p6;

endmodule //dense_resource_ap_fixed_ap_fixed_16_6_5_3_0_config11_s
